name: moimoi
description: Moimoi Microblogging service.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  get_it: ^7.2.0

  freezed_annotation: ^2.0.3
  cached_network_image: ^3.1.0
  provider: ^6.0.1
  firebase_auth: ^4.6.1
  firebase_database: ^10.2.1
  firebase_analytics: ^10.4.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  equatable: ^2.0.3
  image_picker: ^1.0.0
  package_info_plus: ^4.0.1
  shared_preferences: ^2.0.8
  firebase_messaging: ^14.6.1
  google_sign_in: ^6.1.2
  intl: ^0.18.1
  url_launcher: ^6.0.12
  share_plus: ^7.0.1
  google_fonts: ^4.0.4
  firebase_remote_config: ^4.2.1
  firebase_dynamic_links: ^5.3.1
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.1.0
  rxdart: ^0.27.2
  translator: ^0.1.7
  firebase_core: ^2.20.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
    - assets/images/icon-48.png
    - assets/images/icon-480.png
    - assets/images/icon-400.png
    - assets/images/qr.png
    - assets/images/bulb.png
    - assets/images/google_logo.png
    - assets/images/error_image.png

fonts:
  - family: TwitterIcon
    fonts:
      - asset: assets/fonts/icons.ttf
  - family: HelveticaNeue
    fonts:
      - asset: assets/fonts/HelveticaNeue.ttf
      - asset: assets/fonts/HelveticaNeue400.ttf
        weight: 400
      - asset: assets/fonts/HelveticaNeue500.ttf
        weight: 500
      - asset: assets/fonts/HelveticaNeue600.ttf
        weight: 600
      - asset: assets/fonts/HelveticaNeue700.ttf
        weight: 700
      - asset: assets/fonts/HelveticaNeue800.ttf
        weight: 800
      - asset: assets/fonts/HelveticaNeue900.ttf
        weight: 900
      - asset: assets/fonts/HelveticaNeueIt.ttf
        style: italic